---

- name: Check sshuser group exists
  group:
    name: 'sshuser'
    state: present

- name: Set up user accounts
  user:
    name: '{{ item }}'
    groups: "{{ users[item]['groups'] }}"
  with_items: "{{ users.keys() | list }}"

- name: Set up ssh keys
  authorized_key:
    user: '{{ item }}'
    key: "{{ authorized_ssh_keys[item]['key'] }}"
  with_items: "{{ authorized_ssh_keys.keys() | list }}"

- name: Determine removed users
  set_fact:
    host_removed_users: "{{ host_users | difference(users) }}"
  when: ansible_facts.host_users is defined

- name: Delete removed user accounts
  user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ host_removed_users }}"
  when: ansible_facts.host_users is defined

- name: Set final user list
  set_fact:
    host_users: "{{ users.keys() | list }}"