---

- name: Check sshuser group exists
  group:
    name: 'ssh'
    state: present

- name: Set up user accounts
  user:
    name: '{{ item }}'
    groups: "{{ users[item]['groups'] }}"
  with_items: "{{ users.keys() | list }}"

- name: Set up ssh keys
  authorized_key:
    user: '{{ item }}'
    key: "{{ authorized_ssh_keys[item]['key'] }}"
  with_items: "{{ authorized_ssh_keys.keys() | list }}"

- name: Determine existing users
  shell: 'grep ssh /etc/group | cut -d: -f4 | tr "," "\n"'
  changed_when: false 
  register: existing_users

- name: Determine removed users
  set_fact:
    removed_users: "{{ existing_users.stdout_lines | difference(users) }}"

- name: Delete removed user accounts
  user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ removed_users }}"